(head = [and (N > 0) (cons >Ls (head <Ls (N - 1)))])
(tail = [if (N is Ls.len) Ls (tail <Ls N)])
(2num = [coerce X 'num])
(2ls = [coerce X 'cons])
(2str = [coerce X 'string])
(endl = #\newline)
(mac apropos (arg) (arg 2str helpsearch-core @[pr (ellipsize_20:string Name " " (20 ".")) (Name sym helpstr cadr:lines) "\n"]) 'nil)
